name: publish to web

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@master
        - name: setup flutter
          uses: subosito/flutter-action@v2
        - run: flutter --version

        - name: start clean
          run: |
            rm -rf assets/ canvaskit/ icons/ .last_build_id favicon.png flutter.js \
              flutter_bootstrap.js flutter_service_worker.js icons index.html \
              main.dart.js manifest.json version.json

        - name: clone GitaPower
          run: git clone https://github.com/sudeeprp/GitaPower.git
        - name: build to web
          run: |
            cd GitaPower/feeder
            flutter pub get
            flutter build web --release --optimization-level=4 \
              --output ../.. --base-href=/gita-discover/

        - name: cleanup
          run: rm -rf GitaPower

        - name: commit and publish
          run: |
            git config user.name "gita-web-builder[bot]"
            git config user.email "gita-web-builder@users.noreply.github.com"
            git add .
            git commit -m "Web build and publish"
            git push

        - name: trigger GitHub Pages deploy
          run: |
            curl -X POST -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/pages/builds
        